### ISSUE TITLE
FindFailed error: LBAS resupply issue when a disabled base require refuelling

### ISSUE THREAD

**Issue by CripsyBekon** [perryhuynh/kcauto#126]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md):0.4.4
* Viewer/browser: Chrome
* Operating system: Windows 10
* Sikuli version:1.1.2-20171017.103838-37

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: Consistent

#### Issue

The issue happens when the LBAS you plan to use is not in the 1st slot. Due to the nature LBAS airbase strikes, sometimes the base would lose some planes. If the 1st base is disabled, and the second base has planes that usually don't get shot down(i.e toukai), during the LBAS resupply, the first base would be ignored, and the second base doesn't need resupplying, the script would crash with a FindFailed error. 

Reproduction steps:
1. the fleet you use is in fleet 2, fleet 1 needs refuelling but you ignored it
2. manually refuel fleet 2
3. run script
4. script sees fleet 1 needs refueling but ignores it, goes to fleet 2
5. fleet 2 doesn't need refuelling, but it tries to find the resupply button
6. findfailed, crashes and attempts to go back to home. The script will be in a loop from then onwards

#### Log
```
[2018-03-19 12:13:29] Initializing config module
[2018-03-19 12:13:29] Reading config
[2018-03-19 12:13:29] Validating config
[2018-03-19 12:13:29] Starting kancolle-auto!
[log] App.focus:  [4656:Chrome]
[log] App.focus:  [4656:Chrome]
[2018-03-19 12:13:34] At home
[2018-03-19 12:13:37] At home
[2018-03-19 12:13:41] At home
[2018-03-19 12:13:41] Navigating to combat screen.
[log] CLICK on L(204,328)@S(0)[0,0 1366x768] (533 msec)
[log] CLICK on L(277,309)@S(0)[0,0 1366x768] (521 msec)
[log] CLICK on L(724,506)@S(0)[0,0 1366x768] (521 msec)
[2018-03-19 12:14:01] Begin resupplying LBAS groups.
[log] CLICK on L(246,467)@S(0)[0,0 1366x768] (533 msec)
[2018-03-19 12:14:11] Resupplying LBAS group 2.
[log] CLICK on L(697,188)@S(0)[0,0 1366x768] (526 msec)
[2018-03-19 12:14:12] FindFailed: lbas_resupply.png: (30x13) seen at (773, 274) with 1.00 in R[412,66 400x480]@S(0) E:Y, T:1.0
  Line 2754, in file Region.java

[2018-03-19 12:14:12] ** FindFailed error occurred; attempting basic recovery. **
[log] App.focus:  [4656:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
[2018-03-19 12:14:14] Recovery successful.
[log] App.focus:  [4656:Chrome]
[2018-03-19 12:14:19] At side menu
[2018-03-19 12:14:19] Going home.
[log] CLICK on L(88,318)@S(0)[0,0 1366x768] (520 msec)
```

#### Config
```
[Combat]
Enabled = True
Engine = legacy
FleetMode = stf
Formations = 1:combinedfleet_4, 2:combinedfleet_1, 3:combinedfleet_4, 4:combinedfleet_4, 5:combinedfleet_4
LBASGroup1Nodes = 
LBASGroup2Nodes = N, N
LBASGroup3Nodes = 
LBASGroups = 2
Map = E-7
MiscOptions = CheckFatigue, PortCheck
NightBattles = 5:True
NodeSelects = J>N
CombatNodes = 5
RepairLimit = minor
RepairTimeLimit = 0030
RetreatLimit = heavy
```

**Comment by mrmin123** [comment]
@CripsyBekon Try upgrading to 0.4.4, this issue should already be resolved there. Probably related to #117.

**Comment by CripsyBekon** [comment]
alright. i will test it out and give you an update by tomorrow

**Comment by CripsyBekon** [comment]
I tried it again but it still doesn't work. I updated the logs and version. Just in case it is like #117 , i added my sikuli version as well.

**Comment by mrmin123** [comment]
Not sure if this is actually going to resolve the issue since I can't pin it down and I can't reproduce; hopefully the additional delay will fix the problem, or, failing that, the additional console message will help debug.
